api_platform:
  show_webby: false
  formats:
    json: ['application/json']
    html: ['text/html']
  title: "GreenQuest API"
  description: "GreenQuest API"
  version: "1.0.0"
  mapping:
      paths: ["%kernel.project_dir%/src/Entity"]
  swagger:
      versions: [3]
