vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    feed_post_cover:
      uri_prefix: /files/postCover
      upload_destination: '%kernel.project_dir%/public/files/postCover'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

